version: '3.7'
services:
  # cli:
  #   image: node:14-alpine
  #   container_name: reactApp
  #   working_dir: /workspace
  #   volumes:
  #     - ~/workspace/react:/workspace
  #   tty: true
  react:
    image: node:14-alpine
    container_name: ryanship
    working_dir: /app
    command: yarn start
    volumes: 
    - .:/app
    ports:
    - ${APP_PORT}:3000